name: Prod Deploy to SSH Server

on:
  push:
    branches:
      - main
    paths-ignore: ['.vscode/**']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/apps/rca_app
            git stash
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            chmod +x scripts/create_prod_env.sh
            ./scripts/create_prod_env.sh
            rm -rf package-lock.json
            pnpm install
            pnpm run build
            pm2 start ecosystem.config.cjs --only rca-app
