name: Test Deploy to Server (Docker)

on:
  # push:
  #   branches:
  #     -  test
  #   paths-ignore: ['.vscode/**']
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, rcamis, koica-server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Env files
        run: |
          chmod +x scripts/create_test_env.sh
          ./scripts/create_test_env.sh

      - name: Stop and remove existing Docker container
        run: |
          sudo docker stop rca-app-test || true
          sudo docker rm rca-app-test || true

      - name: Build & Run Docker Image
        run: |
          sudo docker build --build-arg APP_PORT=5443 -t rca-app-test .
          sudo docker run -d --name rca-app-test -p 5443:5443 rca-app-test:latest

      - name: Clean Up Repository Files
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
